[theme]
primaryColor = "#8BC34A" 
backgroundColor = "#0D1B2A"
secondaryBackgroundColor = "#1B263B"
textColor = "#E0E1DD"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
